feat/Scrape and Publish PDF receipts
mytiki/client-library-ios pull request #97
Opened 2024-05-08 20:47 UTC by JesseMonteiro

close #78

2024-05-09 12:06 UTC, ricardobrg requested changes

2024-05-09 12:06 UTC, ricardobrg commented on TikiClient/Classes/Email/EmailService.swift
> +        clearEmailIndexList(email: "jessemonteirodev@gmail.com")
remove hardcoded email

2024-05-10 14:45 UTC, JesseMonteiro commented on TikiClient/Classes/Email/EmailService.swift
> +        clearEmailIndexList(email: "jessemonteirodev@gmail.com")
done

2024-05-10 14:50 UTC, ricardobrg approved these changes

2024-05-10 14:59 UTC, merged